### ISSUE TITLE
Tray-API: Add method to update tray icon

### ISSUE THREAD

**Issue by infeo** [cryptomator/integrations-api#13]
Currently the tray api allows to set the tray icon once. It cannot be changed afterwards anymore and thus the consumer cannot adjust the tray icon to changes.

Extending the trayMenuController with a method like `void updateTrayIcon(...)` would allow this.

**Comment by VsevolodGolovanov** [comment]
PR  #14

**Comment by VsevolodGolovanov** [comment]
I guess I need a beta release to finish https://github.com/cryptomator/cryptomator/issues/2557?
