### ISSUE TITLE
More verbose logs

### ISSUE THREAD

**Issue by ACasset** [cryptomator/integrations-api#9]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Make logs more verbose for plugins loading

### Motivation

I am encountering an issue on Cryptomator start with a plugin (the purejava/keepassxc-cryptomator one, which provides a KeychainAccessProvider).
While I do understand that the plugin is likely the issue, I can not see anything related to plugin loading in the Cryptomator logs, even in debug mode.
So, could it be possible to make some more log outputs in the plugins loading chain ?
Thanks!

**Comment by purejava** [comment]
keepassxc-cryptomator has some nice logging features, especially when logging is set to `trace`. In this case you see the communication to KeePassXC and if it get's stuck or not. The plugin getting stuck is bad, as this keeps Cryptomator from launching.

BTW secret-service has different logging levels too.

Enabling debug logging in Cryptomator sets the logging to `trace` for Cryptomator itself, but for none of the other components: https://github.com/cryptomator/cryptomator/blob/fbc598fed7652d7bcc75f19068606b4aba0b34a2/src/main/java/org/cryptomator/logging/LoggerModule.java#L41-L43

With MR https://github.com/cryptomator/integrations-api/pull/10 we'll see which jar was loaded. I think, the OP intended to see more of the plugin logging and I would appreciate this as well.

Could you add this too?

**Comment by overheadhunter** [comment]
> Enabling debug logging in Cryptomator sets the logging to `trace` for Cryptomator itself, but for none of the other components

We don't want the general log level to increase, as this would also lead to a lot of log spam from e.g. Jetty when using the WebDAV volume. But I guess we'll find a way to adjust the loglevel of plugins somehow.

**Comment by purejava** [comment]
An additional info @overheadhunter: I am preparing the next release of keepassxc-cryptomator that will contain timeouts for transactions between the plugin and the KeePassXC database.
The effect is, that a hanging or error prune connection does not keep the Cryptomator UI from coming up.
